/* USER CODE BEGIN Header */
/*******************************************************************************
 * EE 329 A4 Parts D: Reaction Timer
 *******************************************************************************
 * @file           : main.c
 * @brief          : This is a reaction timer game that uses the onboard blue
 *                   LED, onboard push button, and an LCD display
 * project         : EE 329 S'24 Assignment 4
 * authors         : Raheel Rehmatullah and Logan Tom
 * version         : 1
 * date            : 5_1_2024
 * compiler        : STM32CubeIDE v.1.15.0
 * target          : NUCLEO-L4A6ZG
 * clocks          : 4 MHz MSI to AHB2
 * @attention      : (c) 2023 STMicroelectronics.  All rights reserved.
 *******************************************************************************
 * Pin Map:
 *
 * PB7  - Onboard Blue LED
 * PC13 - Onboard pushbutton
 *
 * LCD:
 * PD0 - R/W
 * PD1 - E
 * PD2 - RS
 *
 * PD3 - D4
 * PD4 - D5
 * PD5 - D6
 * PD6 - D7
 *
 *******************************************************************************
 *
 * External Interrupt code generated by ChatGPT 4_29_2024 and subsequently modified
 *
 *******************************************************************************/
/* USER CODE END Header */


#include "main.h"
#include "lcd.h"
#include "stdio.h"
#include "string.h"

uint8_t state = 0;
uint8_t button_flag;

void SystemClock_Config(void);

int main(void){


  __enable_irq();
  HAL_Init();
  SystemClock_Config();
  setup_ext_interrupt();
  setup_rng();
  setup_gpio();
  Lcd_Init();
//
//  Lcd_write_string("EE 329 A4 REACT", 0);
//  Lcd_write_string("PUSH SW TO TRIG", 1);


  //Setting up some variables we need later
  char bottom_string[17];
  uint32_t time_of_button_press = 0;
  uint32_t time_delay;
  //
  setup_TIM2(0xFFFFFFFF);

  while (1){

	  switch(state){
	  case 0:
		  //Reset LED
	      GPIOB->ODR &= ~GPIO_PIN_7;
		  //Reset numbers
		  TIM2->CNT = 0;
		  time_of_button_press = 0;

		  //Reset Text
		  strcpy(bottom_string, "TIME = N.MMM s  ");
		  Lcd_write_string("EE 329 A4 REACT", 0);
		  Lcd_write_string("PUSH SW TO TRIG", 1);
		  //If button is pushed
		  if (button_flag == 1){
			  //Reset button flag
			  button_flag = 0;
			  //Get a random number
			  //25 bits at 4MHz is equal to a maximum time delay of 8 seconds
			  time_delay = (get_random_number() >> (32-25));
			  TIM2->CCR1 = time_delay;
			  //Go to next state
			  state++;
		  }
		  break;
	  case 1:
		  //Print the bottom string
		  Lcd_write_string(bottom_string, 1);
		  //Because we aren't resetting the timer count,
		  //the timer will advance the state when CCR1 IRQ is hit
		  break;
	  case 2:
		  //Print the bottom string
		  if (button_flag == 1){
		  			  //Reset button flag
		  			  button_flag = 0;
		  			  //Get the time of the counter
		  			  time_of_button_press = TIM2->CNT;
		  			  //Charify the Seconds value
		  			  bottom_string[7] = ((time_of_button_press - time_delay) / 4000000) | 0x30 ;
		  			  // If we are dealing with a time more than a second, we'll bother with the rest of the numbers
		  			  if (((time_of_button_press - time_delay) / 4000000) > 0){
		  				 //Charify the 100ms place
		  				 bottom_string[9] = ((time_of_button_press - time_delay) / 400000) % 10| 0x30;
		  				 //10ms place
		  				 bottom_string[10] = ((time_of_button_press - time_delay) / 40000) % 10| 0x30;
		  				 //1ms place
		  				 bottom_string[11] = ((time_of_button_press - time_delay) / 4000) % 10 | 0x30;
		  			  }
		  			  //Update the LCD with all that new text
		  			  Lcd_write_string(bottom_string, 1);
		  			  state++;
		  		  }

		  break;

	  case 3:
		  delay_us(1000000);
		  // Reset when button is pushed
		  if (button_flag == 1){
  			  button_flag = 0;
			  state = 0;
		  }
		  break;
	  }

  }
}

void setup_TIM2( int iDutyCycle ) {
   RCC->APB1ENR1 |= RCC_APB1ENR1_TIM2EN;           // enable clock for TIM2
   TIM2->DIER |= (TIM_DIER_CC1IE | TIM_DIER_UIE);  // enable event gen, rcv CCR1
   TIM2->ARR = 0xFFFFFFFF;                             // ARR = T = counts @4MHz
   TIM2->CCR1 = iDutyCycle;                        // ticks for duty cycle
   TIM2->SR &= ~(TIM_SR_CC1IF | TIM_SR_UIF);       // clr IRQ flag in status reg
   NVIC->ISER[0] |= (1 << (TIM2_IRQn & 0x1F));     // set NVIC interrupt: 0x1F
   __enable_irq();                                 // global IRQ enable
   TIM2->CR1 |= TIM_CR1_CEN;                       // start TIM2 CR1
}

void TIM2_IRQHandler(void) {
   if (TIM2->SR & TIM_SR_CC1IF) {      // triggered by CCR1 event ...
      TIM2->SR &= ~(TIM_SR_CC1IF);     // manage the flag
      GPIOB->ODR |= GPIO_PIN_7;
      state++; //ADvance from state 1 to state 2
   }

}

// Does what it says in the name
void setup_rng(void){
    RCC->AHB2ENR |= RCC_AHB2ENR_RNGEN;
	RNG->CR |= (RNG_CR_RNGEN | RNG_CR_IE);
}

//Gets a random number from the RNG, number is a int32
uint32_t get_random_number(void){

	uint32_t random_number;

	//Get error bits of RNG Status Register
	uint8_t ceis_bit_value = ((RNG->SR & RNG_SR_CEIS_Msk) >> RNG_SR_CEIS_Pos);
	uint8_t seis_bit_value = ((RNG->SR & RNG_SR_SEIS_Msk) >> RNG_SR_SEIS_Pos);

	//and then get data ready bit
	uint8_t data_ready_bit_value = ((RNG->SR & RNG_SR_DRDY_Msk) >> RNG_SR_DRDY_Pos);

	//Check the status for no errors
	if ( (ceis_bit_value + seis_bit_value == 0) && (data_ready_bit_value == 1) ) {
		//Read the RNG data register
		random_number = RNG->DR;
	}
	//Return the number found in the data register
	//If this function returns all 0's, something is wrong with the RNG!
	return(random_number);
}

//Use for setting up external interrupt on user button (PC13
void setup_ext_interrupt(void){

		//Tell the syscfg that we want to use pin C13 for our interrupt
		SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI13_PC;

		// Set EXTI13 (external interrupt) to rising edge trigger
	    EXTI->RTSR1 |= EXTI_RTSR1_RT13;

	    // Enable interrupt on EXTI13
	    EXTI->IMR1 |= EXTI_IMR1_IM13;

	    // Enable EXTI13 interrupt in NVIC
	    NVIC_SetPriority(EXTI15_10_IRQn, 5); // Set priority (adjust as needed)
	    NVIC_EnableIRQ(EXTI15_10_IRQn);
	    __enable_irq(); // global IRQ enable

}

//IRQ Handler for when we press our user button
void EXTI15_10_IRQHandler(void) {
    if (EXTI->PR1 & EXTI_PR1_PIF13) {
        // Clear the pending interrupt flag
        EXTI->PR1 |= (EXTI_PR1_PIF13);
        button_flag = 1; //Sets a global flag
    }
}

//Setups up all basic input and output (button + blue LED)
void setup_gpio(void){
		// configure GPIO pins PC13 for the user button
		// input mode, with pull down
		RCC->AHB2ENR   |=  (RCC_AHB2ENR_GPIOCEN);
		GPIOC->MODER   &= ~(GPIO_MODER_MODE13);
		GPIOC->PUPDR   |= (GPIO_PUPDR_PUPD13_1);

		// configure GPIO pins PB7 and PB8 for:
		// output mode, no pull up or down, high speed,
		RCC->AHB2ENR   |=  (RCC_AHB2ENR_GPIOBEN);
		GPIOB->MODER &= ~(GPIO_MODER_MODE7 | GPIO_MODER_MODE8);
		GPIOB->MODER |= (GPIO_MODER_MODE7_0 | GPIO_MODER_MODE8_0);
		GPIOB->OTYPER  &= ~(GPIO_OTYPER_OT7 | GPIO_OTYPER_OT8);
		GPIOB->PUPDR   &= ~(GPIO_PUPDR_PUPD7 | GPIO_PUPDR_PUPD8);
		GPIOB->OSPEEDR |=  ((3 << GPIO_OSPEEDR_OSPEED7_Pos) | (3 << GPIO_OSPEEDR_OSPEED8_Pos));

}

//For debug
int __io_putchar(int ch) {
    ITM_SendChar(ch);
    return ch;
}


void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  if (HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI48|RCC_OSCILLATORTYPE_MSI;
  RCC_OscInitStruct.HSI48State = RCC_HSI48_ON;
  RCC_OscInitStruct.MSIState = RCC_MSI_ON;
  RCC_OscInitStruct.MSICalibrationValue = 0;
  RCC_OscInitStruct.MSIClockRange = RCC_MSIRANGE_6;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_MSI;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK)
  {
    Error_Handler();
  }
}

void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
